alias exit='echo Do not use exit from tty1\; This is a bug I have no clue on how to fix! Use box poweroff instead.'
alias poweroff='box poweroff'
alias shutdown='box poweroff'
alias net='box net'
alias dhcpeth0='box net dhcp eth0'
alias vim='nvim'
